apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vpxp76f3p-dotnet-basic
  janus-idp.io/tekton: vpxp76f3p-dotnet-basic
  backstage.io/kubernetes-id: vpxp76f3p-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vpxp76f3p-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
